# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fc9065f48c8eb3d28dc8c30b16dfd7ead4ec5e1ec77fea3890cec0fbc5bf84b63674546de88987ac90a60e0308cafbd62a531cd0cb110511db3f392f268bb69

test:
  secret_key_base: add66c92a14b6dbdd080941997b04fca5923ddb2e2f009ffb0e8b2673491b306908359810b5d02cd2aa083ff9e69549a941fefa8b7da79686627a8bb1b26af66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
